//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clanTournament.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GuardianModel
    {
        public int Id { get; set; }
        public string MembershipId { get; set; }
        public string DisplayName { get; set; }
        public int MembershipType { get; set; }
        public int TeamID { get; set; }
    
        public virtual TeamModel TeamModel { get; set; }
    }
}
