//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace clanTournament.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TeamModel
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TeamModel()
        {
            this.GuardianModels = new HashSet<GuardianModel>();
        }
    
        public int Id { get; set; }
        public string TeamName { get; set; }
        public int Seed { get; set; }
        public string ClanName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GuardianModel> GuardianModels { get; set; }
    }
}
